[package]
name = "humlog-interface"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^4.3"
humlog-core={path = "../humlog-core"}